"""Add currency field to transactions

Revision ID: 12392c410d52
Revises: 8c78a894f39b
Create Date: 2025-06-15 13:33:41.487538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12392c410d52'
down_revision: Union[str, None] = '8c78a894f39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add currency column as nullable with default value
    op.add_column('transactions', sa.Column('currency', sa.String(), nullable=True, default='USD'))
    
    # Update existing transactions with default currency (USD)
    op.execute("UPDATE transactions SET currency = 'USD' WHERE currency IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'currency')
    # ### end Alembic commands ###
